name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/heroku@1.0.0
      - name: Deploy
        run: |
          container:login
          container:push -a tosios.demo web
          container:release -a tosios.demo web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
